export const notificationTypes = {
  NOTIFICATION_ON_REGISTER: 'NOTIFICATION_ON_REGISTER',
  NOTIFICATION_REQUEST_PERMISSION: 'NOTIFICATION_REQUEST_PERMISSION',
  NOTIFICATION_CHECK_PERMISSION: 'NOTIFICATION_CHECK_PERMISSION',
  NOTIFICATION_SCHEDULE_FAILURE: 'NOTIFICATION_SCHEDULE_FAILURE',
  NOTIFICATION_SCHEDULE_SUCCESS: 'NOTIFICATION_SCHEDULE_SUCCESS',
  NOTIFICATION_GET_SCHEDULED: 'NOTIFICATION_GET_SCHEDULED',
};
