export const notificationTypes = {
  NOTIFICATION_ON_REGISTER: 'NOTIFICATION_ON_REGISTER',
  NOTIFICATION_SCHEDULE_FAILURE: 'NOTIFICATION_SCHEDULE_FAILURE',
  NOTIFICATION_SCHEDULE_SUCCESS: 'NOTIFICATION_SCHEDULE_SUCCESS',
};
